
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

    {
     "userName":"Kusum",
        "gender":"female",
        "companyName":"Ramanora",
        "departmentName":"Telecomm"
    }

###
GET http://localhost:5000/api/users/6763f18e330847ce553339f8

###
DELETE http://localhost:5000/api/users/67630b3520dc208524b7ac78

###
PUT  http://localhost:5000/api/users/6763f18e330847ce553339f8
Content-Type: application/json

    {
     "userName":"Samruddhi",
     "departmentName": "HR-Admin"
    }